ALTER VIEW dbo.VW_BI_CTB_ANALITICO
AS
SELECT 
    T1.NUMEMP,
    T1.TIPCOL,
    T1.NUMCAD,
    T2.TIPCON,
    T2.CODFIL,
    F.NOMFIL,
    F.CODEST,
    T1.CODCAL,
    CAL.TipCal,
    CAL.PerRef,
    CAL.DatPag,
    CASE 
        WHEN CAL.TipCal = 11        THEN CAL.PerRef
        WHEN CAL.TipCal IN (12,15)  THEN DATEFROMPARTS(YEAR(CAL.DatPag), MONTH(CAL.DatPag), 1)
    END AS PERIODO_REFERENCIA,
    ISNULL(T1.CODCLC, T7.CODCLC)   AS CODCLC,
    T7.nomcon                      AS NOMECLC,
    T6.CCURAT,
    ISNULL(T1.REFEVE, 0)           AS REFEVE,
    ISNULL(T1.VALEVE, 0)           AS VALEVE,
    ISNULL(T6.VALLAN, 0)           AS VALLAN
FROM 
(
    SELECT 
        Z.NUMEMP, Z.TIPCOL, Z.NUMCAD, Z.CODCAL, Z.codrat,
        ISNULL(X.codclc, 0) AS codclc,
        SUM(Z.REFEVE) AS refeve,
        SUM(Z.valeve) AS valeve
    FROM r046ffr Z
    JOIN R008EVC X 
        ON Z.codeve = X.codeve 
       AND X.codtab = 100 
       AND X.tipeve IN (1,2,3)
    GROUP BY Z.NUMEMP, Z.TIPCOL, Z.NUMCAD, Z.CODCAL, Z.codrat, X.codclc
) T1
LEFT JOIN R034FUN T2 
    ON T2.NUMEMP = T1.NUMEMP AND T2.TIPCOL = T1.TIPCOL AND T2.NUMCAD = T1.NUMCAD
JOIN R044CAL CAL
    ON CAL.NUMEMP = T1.NUMEMP 
   AND CAL.CODCAL = T1.CODCAL
   AND CAL.TipCal IN (11,12,15)
LEFT JOIN R048CTB T6 
    ON T6.NUMEMP = T1.NUMEMP AND T6.TIPCOL = T1.TIPCOL AND T6.NUMCAD = T1.NUMCAD 
   AND T6.CODCAL = T1.CODCAL AND T6.CODCLC = T1.CODCLC AND T1.codrat = T6.codrat
LEFT JOIN R048CLC T7 
    ON T7.codclc = T1.codclc
OUTER APPLY (
    SELECT TOP (1) HSI.codfil, HSI.numemp
    FROM r038hfi HSI WITH (NOLOCK)
    WHERE HSI.NUMEMP = T2.NUMEMP
      AND HSI.TIPCOL = T2.TIPCOL
      AND HSI.NUMCAD = T2.NUMCAD
      AND HSI.DATALT <= T6.datlan
    ORDER BY HSI.DATALT DESC
) T3
LEFT JOIN R030FIL F WITH (NOLOCK) 
    ON F.NUMEMP = T3.NUMEMP AND F.CODFIL = T3.CODFIL;
