SELECT TOP 100 PERCENT       
PRR.NUMEMP,   
EMP.NOMEMP,  
hFIL.CODFIL,   
FIL.nomfil AS NOMEFILIAL,   
PRR.TIPCOL,   
PRR.NUMCAD,   
FUN.NOMFUN,   
PRR.MESANO,   
PRR.TIPPRV,   
DEF.DESPRV,   
PRR.SEQPRV,   
PRR.TIPVAL,   
PRR.CODRAT,   
RAT.DESRAT,   
DET.DESVAL,   
PRR.BASPRV,   
PRR.PERVAL,  
PRR.SALANT,   
PRR.SALTRF,   
PRR.AJUPRV,   
PRR.PRVMES,   
PRR.VALPAG,   
PRR.VALADT,   
PRR.VALIND,   
PRR.PAGMAI,   
PRR.AJUMAI,   
PRR.SLDATU,   
PRR.ANB13S,   
PRR.VALPAR       
FROM R146PRR PRR       
LEFT JOIN R030EMP EMP ON EMP.NUMEMP = PRR.NUMEMP      
LEFT JOIN R034FUN FUN ON FUN.NUMEMP = PRR.NUMEMP AND FUN.TIPCOL = PRR.TIPCOL AND FUN.NUMCAD = PRR.NUMCAD      
LEFT JOIN R146DEF DEF ON DEF.TIPPRV = PRR.TIPPRV      
LEFT JOIN R146DET DET ON DET.TIPPRV = PRR.TIPPRV AND DET.TIPVAL = PRR.TIPVAL      
LEFT JOIN R020RAT RAT ON RAT.CODRAT = PRR.CODRAT      
OUTER APPLY (        
    SELECT TOP (1) HSI.codfil , HSI.numemp       
    FROM r038hfi HSI WITH (NOLOCK)        
    WHERE HSI.NUMEMP = FUN.NUMEMP        
      AND HSI.TIPCOL = FUN.TIPCOL        
      AND HSI.NUMCAD = FUN.NUMCAD        
      AND HSI.DATALT < EOMONTH(PRR.MESANO)        
    ORDER BY HSI.DATALT DESC        
) HFIL     
LEFT JOIN R030FIL FIL ON FIL.NUMEMP = HFIL.NUMEMP AND HFIL.CODFIL = FIL.CODFIL     
ORDER BY PRR.MESANO,PRR.NUMEMP   
