-- ============================
-- PARAMETROS GERAIS
-- ============================
DECLARE @NUMEMP   INT  = 2;
DECLARE @DTINI    DATE = '2026-03-01';
DECLARE @DTFIM    DATE = '2026-03-31';

---------------------------------------------------
-- ANALISE OS CÓDIGOS DE CÁLCULO DO MÊS
---------------------------------------------------
SELECT t4.*, t1.*
FROM R044CAL T1
LEFT JOIN r996lsf T4 WITH (NOLOCK)
       ON T4.keynam = T1.TIPCAL
      AND T4.lstnam = 'LTipCal'
WHERE T1.NUMEMP = @NUMEMP
  AND T1.perref = @DTINI
  AND T1.TIPCAL NOT IN (15, 91, 12);
 
---------------------------------------------------
-- CALCULOS COMPLEMENTARES (TIPCAL 15)
---------------------------------------------------
SELECT t4.*, t1.*
FROM R044CAL T1
LEFT JOIN r996lsf T4 WITH (NOLOCK)
       ON T4.keynam = T1.TIPCAL
      AND T4.lstnam = 'LTipCal'
JOIN (
        SELECT DISTINCT NUMEMP, CODCAL
        FROM r046ver
     ) T5
       ON T5.NUMEMP = T1.NUMEMP
      AND T5.CODCAL = T1.CODCAL
WHERE T1.NUMEMP = @NUMEMP
  AND T1.DATPAG BETWEEN @DTINI AND @DTFIM
  AND T1.TIPCAL in (12,15);
 
---------------------------------------------------
-- ANALISE CALCULOS ESPECIFICOS
---------------------------------------------------
--SELECT t4.*, t1.*
--FROM R044CAL T1
--LEFT JOIN r996lsf T4 WITH (NOLOCK)
--       ON T4.keynam = T1.TIPCAL
--      AND T4.lstnam = 'LTipCal'
--WHERE T1.NUMEMP = @NUMEMP
--  AND T1.CODCAL IN (10938, 10953, 10933);
 
---------------------------------------------------
-- ANALISE RESCISAO COMPLEMENTAR
---------------------------------------------------
--SELECT *
--FROM R042RCS
--WHERE NUMEMP = @NUMEMP
--  AND DATPAG BETWEEN @DTINI AND @DTFIM;
 
---------------------------------------------------
-- ANALISE CLCS DO LOTE DOS CALCULOS COMPLEMENTARES
---------------------------------------------------
--SELECT DISTINCT codclc, cplhis, concre, condeb
--FROM R048CTB
--WHERE NUMEMP = @NUMEMP
--  AND DATLAN = @DTINI
--  AND CODCLC IN (
--        SELECT DISTINCT T2.codclc
--        FROM r046ver T1
--        JOIN R008EVC T2
--          ON T1.CODEVE = T2.codeve
--         AND T2.codtab = 100
--        WHERE T1.NUMEMP = @NUMEMP
--          AND T1.CODCAL IN (10939, 10940, 10941, 10943, 10944)
--  );
 
---------------------------------------------------
-- FILTRA CODIGO DE CALCULOS DO LOTE CONTABIL
---------------------------------------------------
SELECT DISTINCT T1.NUMEMP, T1.CODCAL
FROM R048CTB T1
LEFT JOIN R030FIL T2 ON T1.CODFIL = T2.CODFIL
LEFT JOIN R034FUN T3 ON T3.NUMEMP = T1.NUMEMP
                    AND T3.TIPCOL = T1.TIPCOL
                    AND T3.NUMCAD = T1.NUMCAD
LEFT JOIN R018CCU T4 ON T4.NUMEMP = T1.NUMEMP
                    AND T4.CODCCU = T1.CODCCU
WHERE T1.NUMEMP = @NUMEMP
  AND T1.DATLAN BETWEEN @DTINI AND @DTFIM;
 
---------------------------------------------------
-- ANALITICO DO LOTE CONTABIL
---------------------------------------------------
--SELECT DISTINCT 
--       T1.NUMEMP,
--       T1.NUMCAD,
--       T1.DATLAN,
--       T1.CODFIL,
--       T2.NOMFIL,
--       T1.CONCRE,
--       T1.VALLAN,
--       T1.CODCAL,
--       T2.CODEST,
--       T1.CODCLC,
--       T1.CPLHIS,
--       T1.VALLAN AS VALOR,
--       T1.CONDEB,
--       T1.CONCRE
--FROM R048CTB T1
--LEFT JOIN R030FIL T2 ON T1.CODFIL = T2.CODFIL
--LEFT JOIN R034FUN T3 ON T3.NUMEMP = T1.NUMEMP
--                    AND T3.TIPCOL = T1.TIPCOL
--                    AND T3.NUMCAD = T1.NUMCAD
--LEFT JOIN R018CCU T4 ON T4.NUMEMP = T1.NUMEMP
--                    AND T4.CODCCU = T1.CODCCU
--WHERE T1.NUMEMP = @NUMEMP
--  AND T1.DATLAN BETWEEN @DTINI AND @DTFIM
--ORDER BY 1, 3, 6;

-- ============================
-- PARAMETROS GERAIS
-- ============================
--DECLARE @NUMEMP   INT  = 2;
--DECLARE @DTINI    DATE = '2026-01-01';
--DECLARE @DTFIM    DATE = '2026-01-31';

---------------------------------------------------
-- FILTRA CODIGO DE CALCULOS DO LOTE CONTABIL
---------------------------------------------------
/*SELECT T1.NUMEMP,T1.DATLAN,T1.CODFIL,T2.NOMFIL,T2.CODEST,T1.CODCLC,T1.CPLHIS,T1.VALLAN AS VALOR,T1.CONDEB,T1.CONCRE
FROM R048CTB T1
LEFT JOIN R030FIL T2 ON T1.CODFIL = T2.CODFIL
LEFT JOIN R034FUN T3 ON T3.NUMEMP = T1.NUMEMP
                    AND T3.TIPCOL = T1.TIPCOL
                    AND T3.NUMCAD = T1.NUMCAD
LEFT JOIN R018CCU T4 ON T4.NUMEMP = T1.NUMEMP
                    AND T4.CODCCU = T1.CODCCU
WHERE T1.NUMEMP = @NUMEMP
  AND T1.DATLAN BETWEEN @DTINI AND @DTFIM */--and t1.codcal = 10963

  -------------------

  -- ============================
-- PARAMETROS GERAIS
-- ============================
-- Contabilização comparada com a ficha financeira
--DECLARE @NUMEMP   INT  = 4;
--DECLARE @DTINI    DATE = '2026-01-01';
--DECLARE @DTFIM    DATE = '2026-01-31';

SELECT 
	T1.NUMEMP, T1.TIPCOL, T1.DATLAN, T1.CODFIL, T2.NOMFIL, T2.CODEST, T1.CODCLC, T1.CPLHIS, T1.VALLAN AS VALOR,T1.CONDEB, T1.CONCRE, T1.CODRAT, T1.CODCAL, T5.CODEVE, T5.DESEVE, ISNULL(T6.REFEVE,0) AS REFEVE, ISNULL(T6.VALEVE,0) AS VALEVE, T7.keynam as CARACTERISTICA, T5.tipeve as COD_TIPO, T8.valkey as TIPOEVENTO
	FROM R048CTB T1
JOIN R030FIL T2 ON T1.CODFIL = T2.CODFIL 
JOIN R034FUN T3 ON T3.NUMEMP = T1.NUMEMP AND T3.TIPCOL = T1.TIPCOL AND T1.NUMCAD = T3.NUMCAD
LEFT JOIN R018CCU T4 ON T4.NUMEMP = T1.NUMEMP AND T1.CODCCU = T4.CODCCU 
LEFT JOIN R008EVC T5 ON T5.CodCLC = T1.codclc AND T5.codtab = 100
LEFT JOIN R046FFR T6 ON T6.NUMEMP = T1.NUMEMP AND T6.TIPCOL = T1.TIPCOL AND T6.NUMCAD = T1.NUMCAD AND T6.codcal = T1.CODCAL AND T6.CODEVE = T5.CODEVE
LEFT JOIN r996lsf T7 ON T7.lstnam ='lcrteve' AND T7.keynam = T5.crteve  
LEFT JOIN r996lsf T8 ON T8.lstnam ='ltipevt' AND T8.keynam = T5.tipeve
WHERE T1.NUMEMP = @NUMEMP AND T1.DATLAN BETWEEN @DTINI AND @DTFIM AND T6.VALEVE > 0
--AND T1.NUMEMP = 2--AND T1.NUMEMP = 2 and t1.codfil = 2004 --AND T1.CODCLC IN (select CODCLC from r048clc where nomcon like '%FÉRIAS%' and tiplan = 'D').
--GROUP BY T1.NUMEMP,/*T1.NUMCAD,T3.NOMFUN,*/T1.CODFIL,T2.NOMFIL,T2.CODEST,CODCLC,CPLHIS,CONDEB,CONCRE
ORDER BY T1.CODCLC


--SELECT T1.NUMEMP, T1.TIPCOL, T1.NUMCAD, T2.TIPCON, T2.CODFIL, T3.NOMFIL, T3.CODEST, T1.CODCAL, T1.CODEVE, T5.DESEVE, T5.TIPEVE, ISNULL(T5.CODCLC,0) AS CODCLC, ISNULL(T1.REFEVE,0) AS REFEVE, ISNULL(T1.VALEVE,0) AS VALEVE, ISNULL(T6.VALLAN,0) AS VALLAN
--FROM R046VER T1
--LEFT JOIN R034FUN T2 ON T2.NUMEMP = T1.NUMEMP AND T2.TIPCOL = T1.TIPCOL AND T2.NUMCAD = T1.NUMCAD-
--LEFT JOIN R030FIL T3 ON T3.CODFIL = T2.CODFIL
--LEFT JOIN R044CAL T4 ON T4.NUMEMP = T1.NUMEMP AND T4.CODCAL = T1.CODCAL
--LEFT JOIN R008EVC T5 ON T5.CODEVE = T1.CODEVE AND T5.codtab = 100
--LEFT JOIN R048CTB T6 ON T6.NUMEMP = T1.NUMEMP AND T6.TIPCOL = T1.TIPCOL AND T6.NUMCAD = T1.NUMCAD AND T6.CODCAL = T1.CODCAL AND T6.CODCLC = T5.CODCLC
--WHERE T1.CODCAL IN (21351,21357)

----- Relação de calculo corrigido histórico de filial -----
/*DECLARE @NUMEMP   INT  = 2;
DECLARE @DTINI    DATE = '2026-01-01';
DECLARE @DTFIM    DATE = '2026-01-31';
SELECT T1.NUMEMP, T1.TIPCOL, T1.NUMCAD, T2.TIPCON, T2.CODFIL, F.NOMFIL, F.CODEST, T1.CODCAL, /*T1.CODEVE, T5.DESEVE, T5.TIPEVE*/T5.CODCLC, ISNULL(T5.CODCLC,0) AS CODCLC, T6.CCURAT, ISNULL(T1.REFEVE,0) AS REFEVE, ISNULL(T1.VALEVE,0) AS VALEVE, ISNULL(T6.VALLAN,0) AS VALLAN
FROM R046VER T1
LEFT JOIN R034FUN T2 ON T2.NUMEMP = T1.NUMEMP AND T2.TIPCOL = T1.TIPCOL AND T2.NUMCAD = T1.NUMCAD
LEFT JOIN R044CAL T4 ON T4.NUMEMP = T1.NUMEMP AND T4.CODCAL = T1.CODCAL
LEFT JOIN R008EVC T5 ON T5.CODEVE = T1.CODEVE AND T5.codtab = 100
LEFT JOIN R048CTB T6 ON T6.NUMEMP = T1.NUMEMP AND T6.TIPCOL = T1.TIPCOL AND T6.NUMCAD = T1.NUMCAD AND T6.CODCAL = T1.CODCAL AND T6.CODCLC = T5.CODCLC
OUTER APPLY (              
    SELECT TOP (1) HSI.codfil , HSI.numemp             
    FROM r038hfi HSI WITH (NOLOCK)              
    WHERE HSI.NUMEMP = T2.NUMEMP              
      AND HSI.TIPCOL = T2.TIPCOL              
      AND HSI.NUMCAD = T2.NUMCAD              
      AND HSI.DATALT <= T6.datlan              
    ORDER BY HSI.DATALT DESC              
)  T3
LEFT JOIN R030FIL F WITH (NOLOCK)              
    ON F.NUMEMP = T3.NUMEMP AND F.CODFIL = T3.CODFIL  
WHERE T1.CODCAL IN (21351,21357) AND T1.NUMCAD = 20003217*/
--DECLARE @NUMEMP   INT  = 2;
--DECLARE @DTINI    DATE = '2026-01-01';
--DECLARE @DTFIM    DATE = '2026-01-31';
SELECT T1.NUMEMP, T1.TIPCOL, T1.NUMCAD, T2.TIPCON, T2.CODFIL, F.NOMFIL, F.CODEST, T1.CODCAL, /*T1.CODEVE, T5.DESEVE, T5.TIPEVE*/
ISNULL(t1.CODCLC,T7.CODCLC) AS CODCLC, T7.nomcon AS NOMECLC,  T6.CCURAT, ISNULL(T1.REFEVE,0) AS REFEVE, ISNULL(T1.VALEVE,0) AS VALEVE, ISNULL(T6.VALLAN,0) AS VALLAN
FROM 
(SELECT NUMEMP,TIPCOL,NUMCAD,CODCAL,codrat,isnull(x.codclc,0) as codclc,SUM(REFEVE) AS refeve,sum(valeve) as valeve 
FROM r046ffr Z JOIN R008EVC X ON Z.codeve = X.codeve AND X.codtab = 100
WHERE NUMEMP = @NUMEMP AND CODCAL IN (21363,21364,21365,21369
)
group by NUMEMP,TIPCOL,NUMCAD,CODCAL,codrat,x.codclc)
T1
LEFT JOIN R034FUN T2 ON T2.NUMEMP = T1.NUMEMP AND T2.TIPCOL = T1.TIPCOL AND T2.NUMCAD = T1.NUMCAD
LEFT JOIN R044CAL T4 ON T4.NUMEMP = T1.NUMEMP AND T4.CODCAL = T1.CODCAL
LEFT JOIN R048CTB T6 ON T6.NUMEMP = T1.NUMEMP AND T6.TIPCOL = T1.TIPCOL AND T6.NUMCAD = T1.NUMCAD AND T6.CODCAL = T1.CODCAL AND T6.CODCLC = t1.CODCLC and t1.codrat = t6.codrat
left join r048clc T7 ON T7.codclc = T1.codclc
OUTER APPLY (              
    SELECT TOP (1) HSI.codfil , HSI.numemp             
    FROM r038hfi HSI WITH (NOLOCK)              
    WHERE HSI.NUMEMP = T2.NUMEMP              
      AND HSI.TIPCOL = T2.TIPCOL              
      AND HSI.NUMCAD = T2.NUMCAD              
      AND HSI.DATALT <= T6.datlan              
    ORDER BY HSI.DATALT DESC              
)  T3
LEFT JOIN R030FIL F WITH (NOLOCK)              
    ON F.NUMEMP = T3.NUMEMP AND F.CODFIL = T3.CODFIL  
WHERE T1.CODCAL IN (21363,21364,21365,21369
) --and t2.codfil = 2045 and t7.codclc = 165
order by 13

----- LOTE CONTABIL -----
-- ============================
-- PARAMETROS GERAIS
-- ============================
-- Contabilização comparada com a ficha financeira
--DECLARE @NUMEMP   INT  = 2;
--DECLARE @DTINI    DATE = '2026-02-01'
--DECLARE @DTFIM    DATE = '2026-02-28';
SELECT 
	T1.NUMEMP,T1.DATLAN,T1.CODFIL,T2.NOMFIL,T2.CODEST,CODCLC,CPLHIS,VALLAN AS VALOR,CONDEB,CONCRE
	--t1.*
	FROM R048CTB T1
JOIN R030FIL T2 ON T1.CODFIL = T2.CODFIL 
JOIN R034FUN T3 ON T3.NUMEMP = T1.NUMEMP AND T3.TIPCOL = T1.TIPCOL AND T1.NUMCAD = T3.NUMCAD
LEFT JOIN R018CCU T4 ON T4.NUMEMP = T1.NUMEMP AND T1.CODCCU = T4.CODCCU
WHERE T1.NUMEMP = @NUMEMP AND T1.DATLAN BETWEEN @DTINI AND @DTFIM --AND t1.codclc = 119 AND t1.codfil = 2056
--GROUP BY T1.NUMEMP,/*T1.NUMCAD,T3.NOMFUN,*/T1.CODFIL,T2.NOMFIL,T2.CODEST,CODCLC,CPLHIS,CONDEB,CONCRE
ORDER BY 1,3,6,8




--select * from r046ffr where CODCAL IN (10960,10962,10963,10966,10986,10987) and codeve = 2250

--select * from r008evc
/*DECLARE @NUMEMP   INT  = 3;
DECLARE @DTINI    DATE = '2026-01-01'
DECLARE @DTFIM    DATE = '2026-01-31';
SELECT 
	T1.NUMEMP,T1.DATLAN,T1.CODFIL,T2.NOMFIL,T2.CODEST,CODCLC,CPLHIS,VALLAN AS VALOR,CONDEB,CONCRE
	--t1.*
	FROM R048CTB T1
JOIN R030FIL T2 ON T1.CODFIL = T2.CODFIL 
JOIN R034FUN T3 ON T3.NUMEMP = T1.NUMEMP AND T3.TIPCOL = T1.TIPCOL AND T1.NUMCAD = T3.NUMCAD
LEFT JOIN R018CCU T4 ON T4.NUMEMP = T1.NUMEMP AND T1.CODCCU = T4.CODCCU
WHERE T1.NUMEMP = @NUMEMP AND T1.DATLAN BETWEEN @DTINI AND @DTFIM AND t1.numcad in (30013649
ORDER BY 1,3,6,8*/


--select t1.* from r046ver t1
--left join r034fun t2 on t2.numemp = t1.numemp and t2.tipcol = t1.tipcol and t2.numcad = t1.numcad
--where t2.codfil = 2029 and t1.codcal in (21351,21357)


--select * from r038hfi where numcad = 020018814

--select * from r048ctb where codcal = 21360 and codfil = 2045 and codclc = 121 order by vallan

